### ISSUE TITLE
Error: ta-libc.h No such file or directory. Windows install

### ISSUE THREAD

**Issue by RobinCabannes** [mrjbq7/ta-lib#139]
As I mentionned in the title, I failed installing the librairy. The message raised was: ta-lic.h No such file or directory. 
I know that It is written that "This typically means that it can't find the underlying TA-Lib library, a dependency which needs to be installed." 
But how to install the dependency which is needed?
Thank you in advance for your help,
Robin

**Comment by mrjbq7** [comment]
Well, you need to decide if you are using 32-bit or 64-bit Python on Windows.

If 32-bit:

* Follow the directions in the [README](https://github.com/mrjbq7/ta-lib/blob/master/README.md#windows).

If 64-bit:

* You have to compile the underlying ``ta-lib`` C library yourself, some [directions are here](https://github.com/mrjbq7/ta-lib/issues/127#issuecomment-280222942).

**Comment by RobinCabannes** [comment]
Indeed, thank you. I've finally managed this issue. But now, I have an error:
fatal error LNK1117: erreur de syntaxe dans l'option 'MANIFEST:EMBED, ID=2'
Do you know how to solve it?
Thanks again

**Comment by mrjbq7** [comment]
I assume thats while building the ``ta-lib`` C library? I'm not sure, sorry.

**Comment by RobinCabannes** [comment]
Yes. It seems it looks like this topic:
https://social.msdn.microsoft.com/Forums/vstudio/en-US/966cf58b-ee8b-4333-810d-dd81ff7f0b3d/getting-manifest-error-in-dll-project-upgraded-to-vs2012-from-vs2008?forum=vcgeneral
But I feel difficulties in finding "properties > Linker > Manifest" of the project.. Is there a properties tab in Visual Studio?
Thanks

**Comment by RobinCabannes** [comment]
Finally I don't know how but I passed this issue. However, now, I have this error:
fatal error LNK1181: impossible d'ouvrir le fichier en entrée 'ucrt.lib'
:(

**Comment by jmatzen** [comment]
What a load of crap.

**Comment by mrjbq7** [comment]
I'm sorry you're having this problem, but I am not the author of the ta-lib C library.  I am only providing and supporting this python wrapper for it.  I have tried to provide installation instructions on Windows for 64-bit because they don't support binary release on that for some reason, but it is not my area of expertise.

**Comment by TonyNT8** [comment]
-Unzip the downloaded file to 
C:\ta-lib

Go to folder
C:\ta-lib\c\include

Rename ta_libc.h to ta-libc.h (or copy paste file to have them both)
Try installing it again

--and optionally yell at the guy that made the typo

**Comment by mrjbq7** [comment]
Wow thats awful.  I didn't notice the typo and clearly don't test enough on Windows.

I've fixed and uploaded version 0.4.16 that hopefully fixes that installation issue.

**Comment by rebeltrader2018** [comment]
If you are still having issues getting ta-lib installed after you've compiled it for 64bit then do the following.  
Setup.py for ta-lib is looking for a hardcoded path.  Therefore, you can either modify the installation script (setup.py) and point to where your ta-lib resides or unzip the contents to c:\ta-lib. From below you can clearly see the that is looking for the libs directory (.lib is what it wants and that will show up after you compile with nmake).    

Here is the line of code from setup.py
if sys.platform == "win32":
    platform_supported = True
    lib_talib_name = 'ta_libc_cdr'
    include_dirs = [r"c:\ta-lib\c\include"]
    lib_talib_dirs = [r"c:\ta-lib\c\lib"]

Rocky Phagura

**Comment by viper7882** [comment]
To me, the most convenient way is:
Download TA_Lib‑0.4.21‑cp39‑cp39‑win_amd64.whl from http://www.lfd.uci.edu/~gohlke/pythonlibs/#ta-lib.
And use command
```
pip install TA_Lib‑0.4.21‑cp39‑cp39‑win_amd64.whl
```

**Comment by DasherBro** [comment]
> -Unzip the downloaded file to C:\ta-lib -Go to folder C:\ta-lib\c\include -Rename ta_libc.h to ta-libc.h (or copy paste file to have them both) -Try installing it again (Add C:\ta-lib\c\include to PATH in case it fails)

this worked for me
and 1 more thing to mention. i'd python 3.8 and 3.10 installed, 3.10 gave me all the trouble, i did with 3.8.whl file

**Comment by mrjbq7** [comment]
What version is not working for you?

It should be looking for ta_libc.h

```
#if defined(WIN32) || defined(MS_WINDOWS)
#include "ta_libc.h"
#else
```

**Comment by KonssnoK** [comment]
using python3.10 on win11 still the same error occurs.
had to put 
TA_Lib-0.4.26-cp310-cp310-win_amd64.whl
in the requirements.

This issue should be reopened.

**Comment by mrjbq7** [comment]
What is the issue that needs to be reopened?

If you are installing from source, you need the underlying TA-Lib C library.

Instructions are in the README.

**Comment by KonssnoK** [comment]
well the majority of environments are now 64bits, when doing pip install ta-lib you will get an error due to the underlying module not compiling correctly. 🤔 
i thought installation should be out of the box, without having to rely on externally compiled sources (which changes each time you change environment).

**Comment by Gowthamrasu** [comment]
_ta_lib.obj : error LNK2001: unresolved external symbol TA_GetVersionString
      build\lib.win-amd64-cpython-311\talib\_ta_lib.cp311-win_amd64.pyd : fatal error LNK1120: 339 unresolved externals
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX86\\x64\\link.exe' failed with exit code 1120
      
      
      how to resolve this guys. My python version is 3.11

**Comment by SunUltraSparc** [comment]
For windows users its in the README

##### Windows

Download [ta-lib-0.4.0-msvc.zip](http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-msvc.zip)
and unzip to ``C:\ta-lib``.

> This is a 32-bit binary release.  If you want to use 64-bit Python, you will
> need to build a 64-bit version of the library. Some unofficial (**and
> unsupported**) instructions for building on 64-bit Windows 10, here for
> reference:
>
> 1. Download and Unzip ``ta-lib-0.4.0-msvc.zip``
> 2. Move the Unzipped Folder ``ta-lib`` to ``C:\``
> 3. Download and Install Visual Studio Community (2015 or later)
>    * Remember to Select ``[Visual C++]`` Feature
> 4. Build TA-Lib Library
>    * From Windows Start Menu, Start ``[VS2015 x64 Native Tools Command
>      Prompt]``
>    * Move to ``C:\ta-lib\c\make\cdr\win32\msvc``
>    * Build the Library ``nmake``

You might also try these unofficial windows binaries for both 32-bit and
64-bit:

https://www.lfd.uci.edu/~gohlke/pythonlibs/#ta-lib

**Comment by karansoi** [comment]
> For windows users its in the README
> 
> ##### Windows
> Download [ta-lib-0.4.0-msvc.zip](http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-msvc.zip) and unzip to `C:\ta-lib`.
> 
> > This is a 32-bit binary release.  If you want to use 64-bit Python, you will
> > need to build a 64-bit version of the library. Some unofficial (**and
> > unsupported**) instructions for building on 64-bit Windows 10, here for
> > reference:
> > 
> > 1. Download and Unzip `ta-lib-0.4.0-msvc.zip`
> > 2. Move the Unzipped Folder `ta-lib` to `C:\`
> > 3. Download and Install Visual Studio Community (2015 or later)
> >    
> >    * Remember to Select `[Visual C++]` Feature
> > 4. Build TA-Lib Library
> >    
> >    * From Windows Start Menu, Start `[VS2015 x64 Native Tools Command Prompt]`
> >    * Move to `C:\ta-lib\c\make\cdr\win32\msvc`
> >    * Build the Library `nmake`
> 
> You might also try these unofficial windows binaries for both 32-bit and 64-bit:
> 
> https://www.lfd.uci.edu/~gohlke/pythonlibs/#ta-lib

where can 64 bit version of the zipped folder for this library be found. Appreciate your help..

**Comment by lanceyliao** [comment]
This works.
``
copy c:\ta-lib\c\lib\ta_libc_cdr.lib c:\ta-lib\c\lib\ta_lib.lib
```

```
name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.12']
      fail-fast: false
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install system dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential wget
        sudo locale-gen zh_CN.GB18030

    - name: Install TA-Lib C Library (Linux)
      if: runner.os == 'Linux'
      run: |
        cd /tmp
        wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
        tar -xzf ta-lib-0.4.0-src.tar.gz
        cd ta-lib/
        ./configure --prefix=/usr
        make
        sudo make install
        
    - name: Install TA-Lib C Library (Windows)
      if: runner.os == 'Windows'
      run: |
        curl -L -o ta-lib-msvc.zip http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-msvc.zip
        7z x ta-lib-msvc.zip -oc:\
        cd c:\ta-lib\c\make\cdr\win32\msvc
        cmd /c "`"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat`" && nmake"
        copy c:\ta-lib\c\lib\ta_libc_cdr.lib c:\ta-lib\c\lib\ta_lib.lib
        
    - name: Install base Python packages
      run: |
        python -m pip install pip wheel numpy -U
        
    - name: Install TA-Lib (Linux)
      if: runner.os == 'Linux'
      run: |
        pip install ta-lib==0.5.3
        
    - name: Install TA-Lib (Windows)
      if: runner.os == 'Windows'
      env:
        LIB: c:\ta-lib\c\lib
        INCLUDE: c:\ta-lib\c\include
      run: |
        pip install ta-lib==0.5.3
```

**Comment by lanceyliao** [comment]
```
name: TA-Lib Installation Matrix Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.12']
        install-method: [conda, make, msi, wheel]
        exclude:
          # Linux 不使用 msi 和 wheel 方式
          - os: ubuntu-latest
            install-method: msi
          - os: ubuntu-latest
            install-method: wheel
      fail-fast: false
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v2
    
    ###########################################
    # 环境设置与 TA-Lib 安装 (按安装方法分组)
    ###########################################

    # Conda
    ## 方法 1: Conda 安装 TA-Lib (Linux/Windows)
    - name: Set up Conda environment
      if: matrix.install-method == 'conda'
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ matrix.python-version }}
        channels: conda-forge,defaults
        channel-priority: strict
        activate-environment: test
        auto-activate-base: false
    
    - name: Install TA-Lib (Conda)
      if: matrix.install-method == 'conda'
      shell: bash -l {0}
      run: |
        conda install -y -c conda-forge ta-lib
        pip install numpy pytest 

    # 非Conda
    - name: Set up Python (非Conda)
      if: matrix.install-method != 'conda'
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install base Python packages
      if: matrix.install-method != 'conda'
      run: |
        python -m pip install wheel numpy -U
    
    ## 方法 2: Linux Make 编译安装 TA-Lib    
    - name: Install TA-Lib (Linux Make)
      if: runner.os == 'Linux' && matrix.install-method == 'make'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential wget
        sudo locale-gen zh_CN.GB18030
        cd /tmp
        wget https://github.com/ta-lib/ta-lib/releases/download/v0.6.4/ta-lib-0.6.4-src.tar.gz
        tar -xzf ta-lib-0.6.4-src.tar.gz
        cd ta-lib-0.6.4/
        ./configure --prefix=/usr
        make
        sudo make install
        pip install ta-lib

    ## 方法 3: Windows NMake 编译安装 TA-Lib
    - name: Install TA-Lib (Windows NMake)
      if: runner.os == 'Windows' && matrix.install-method == 'make'
      env:
        LIB: c:\ta-lib\c\lib
        INCLUDE: c:\ta-lib\c\include
      run: |
        curl -L -o ta-lib-msvc.zip https://github.com/TA-Lib/ta-lib/releases/download/v0.4.0/ta-lib-0.4.0-msvc.zip
        7z x ta-lib-msvc.zip -oc:\
        cd c:\ta-lib\c\make\cdr\win32\msvc
        cmd /c "`"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat`" && nmake"
        copy c:\ta-lib\c\lib\ta_libc_cdr.lib c:\ta-lib\c\lib\ta_lib.lib
        pip install ta-lib==0.5.3

    ## 方法 4: Windows MSI 安装 TA-Lib
    - name: Install TA-Lib (Windows MSI)
      if: runner.os == 'Windows' && matrix.install-method == 'msi'
      run: |
        curl -L -o ta-lib-msvc.msi https://github.com/ta-lib/ta-lib/releases/download/v0.6.4/ta-lib-0.6.4-windows-x86_${{ runner.arch == 'X64' && '64' || '32' }}.msi
        msiexec /i ta-lib-msvc.msi /quiet /qn
        pip install ta-lib

    ## 方法 5: Windows Wheel 安装 TA-Lib
    - name: Install TA-Lib (Windows Wheel)
      if: runner.os == 'Windows' && matrix.install-method == 'wheel'
      run: |
        $wheelFile = "ta_lib-0.6.3-cp312-cp312-win_$($env:RUNNER_ARCH -eq 'X64' ? 'amd64' : 'arm64').whl"
        curl -L -o $wheelFile https://github.com/cgohlke/talib-build/releases/download/v0.6.3/$wheelFile
        pip install ./$wheelFile

```
