### ISSUE TITLE
install with bitbucket pipeline

### ISSUE THREAD

**Issue by zero1ne** [mrjbq7/ta-lib#289]
I tried to install ta-lib in bitbucket pipeline, but the following errors are occurred.

```
ERROR: Failed building wheel for TA-Lib
  Running setup.py clean for TA-Lib
  Building wheel for pycparser (setup.py): started
  Building wheel for pycparser (setup.py): finished with status 'done'
  Created wheel for pycparser: filename=pycparser-2.19-py2.py3-none-any.whl size=111029 sha256=e8358861ebd347bb7aca69d5774ea7b8f9adf1138a4459644c646477c3f80588
  Stored in directory: /root/.cache/pip/wheels/f2/9a/90/de94f8556265ddc9d9c8b271b0f63e57b26fb1d67a45564511
Successfully built pprint pycparser
Failed to build TA-Lib
Installing collected packages: configparser, six, pycparser, cffi, cryptography, jwt, python-dateutil, pytz, pandas, pprint, certifi, idna, chardet, urllib3, requests, coverage, codecov, wcwidth, attrs, more-itertools, zipp, importlib-metadata, py, pyparsing, packaging, pluggy, pytest, pytest-cov, TA-Lib
    Running setup.py install for TA-Lib: started
    Running setup.py install for TA-Lib: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3bv3hfir/TA-Lib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3bv3hfir/TA-Lib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-zhw08r9w/install-record.txt --single-version-externally-managed --compile
         cwd: /tmp/pip-install-3bv3hfir/TA-Lib/
    Complete output (27 lines):
    /tmp/pip-install-3bv3hfir/TA-Lib/setup.py:79: UserWarning: Cannot find ta-lib library, installation may fail.
      warnings.warn('Cannot find ta-lib library, installation may fail.')
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/talib
    copying talib/abstract.py -> build/lib.linux-x86_64-3.7/talib
    copying talib/test_data.py -> build/lib.linux-x86_64-3.7/talib
    copying talib/test_stream.py -> build/lib.linux-x86_64-3.7/talib
    copying talib/test_func.py -> build/lib.linux-x86_64-3.7/talib
    copying talib/stream.py -> build/lib.linux-x86_64-3.7/talib
    copying talib/test_pandas.py -> build/lib.linux-x86_64-3.7/talib
    copying talib/__init__.py -> build/lib.linux-x86_64-3.7/talib
    copying talib/deprecated.py -> build/lib.linux-x86_64-3.7/talib
    copying talib/test_abstract.py -> build/lib.linux-x86_64-3.7/talib
    running build_ext
    building 'talib._ta_lib' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/talib
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/lib/python3.7/site-packages/numpy/core/include -I/usr/include -I/usr/local/include -I/opt/include -I/opt/local/include -I/usr/local/include/python3.7m -c talib/_ta_lib.c -o build/temp.linux-x86_64-3.7/talib/_ta_lib.o
    talib/_ta_lib.c:526:10: fatal error: ta-lib/ta_defs.h: No such file or directory
     #include "ta-lib/ta_defs.h"
              ^~~~~~~~~~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3bv3hfir/TA-Lib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3bv3hfir/TA-Lib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-zhw08r9w/install-record.txt --single-version-externally-managed --compile Check the logs for full command output
```

This is my pipeline configuration file, and `TA-Lib` is in requiremets.txt file.
```
# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: python:3.7.5

pipelines:
  default:
    - step:
        deployment: test
        script: # Modify the commands below to build your repository.
          - pip install --upgrade pip
          - pip install numpy
          - pip install -r requirements.txt
          - pytest --cov=./ ./tests/
```

Is there anyone who tried to set this library to bitbucket? I already read the guide in README in this repo, and tried serveral ways to solve this problem such as adding `apt-get install python3-dev` statement, but still cannot solve this error.
